---
title: "Big Data Indicators"
output:
  html_document:
    toc: false
    toc_float: false
---
Презентация результатов проекта по оценке **высокочастотных индикаторов экономических ожиданий населения** на основе больших данных.  

Основой для расчета индикаторов являются комментарии Интернет-пользователей к статьям в крупнейших экономических СМИ по заданным темам.   
Методологическая база представлена в журнале "Вопросы экономики", №6, 2017 - [Голощапова, Андреев (2017). Оценка инфляционных ожиданий российского населения методами машинного обучения.](http://www.vopreco.ru/rus/year.files/n6_2017.html#an5)  

 

Ключевые преимущества подхода к оценке экономических ожиданий на основе больших данных относительно подхода, основанного на опросах домохозяйств:  

- **Точность**. Учет интенсивности ожиданий населения, непосредственно относящихся к заданной теме
- **Охват**. В настоящий момент индикаторы учитывают мнение более 36 000 уникальных пользователей Интернета с возможностью значительного дальнейшего увели-чения
- **Своевременность**. Возможность обновления индикаторов в реальном времени. Все индикаторы рассчитываются на ежедневной основе с возможностью дальнейшей дезагрегации. Обновление результатов расчета индикаторов на сайте происходит каждый месяц. 
- **Опережение**. Опережение индикаторов, строящихся на основе опросов населения примерно на 1 месяц (за счет временного лага, требуемого на сбор и обработку данных личных интервью). 
- **Сопоставимость**. Возможность обеспечить сопоставимость расчетов во времени. При изменении методики расчета все результаты могут быть скорректированы.
- **Низкие издержки**. Стоимость построения системы сбора, обработки и хранения информации для расчета индикаторов несопоставимо ниже затрат на проведение опросов.
